### ISSUE TITLE
"Jumper" feature

### ISSUE THREAD

**Issue by viniam** [ImAxel0/SOTFmenu#2]
Hey there, can you add the jumper feature found in [this mod](https://modapi.survivetheforest.net/mod/14/jumper)? I've always found it to be really useful without breaking the game too much.

**Comment by viniam** [comment]
Maybe [this mod](https://www.nexusmods.com/sonsoftheforest/mods/65) does that.

**Comment by ImAxel0** [comment]
I'm not sure I'm able to do that, but why would I add it if there is already one mod which does that?

**Comment by viniam** [comment]
Yeah, I didn't know about that mod when I made this Issue, the one I said work as intended, thank you for your response!
