### ISSUE TITLE
BUG: Cannot find local player

### ISSUE THREAD

**Issue by tmenant** [ImAxel0/SOTFmenu#4]
When i run `Launch SOFT Mod Menu.exe`,  the game opens as expected, and a terminal opens then enter in infinite loop, displaying this :

```
Searching Required Things...
[+] Found GameAssembly at; 7ffb44....
[-] Cannot find local player

Searching Required Things...
[+] Found GameAssembly at; 7ffb44....
[-] Cannot find local player

...
```

Then, when I try to run a save (online), the game crash and the console closes

Notes:
It's the first time I try to use this mod, it doesn't work by downloading it via Thunderstore mod Manager.
My OS is windows 10
I followed the instructions that you wrote on [this page](https://thunderstore.io/c/sons-of-the-forest/p/ImAxel0/SOTF_Menu/)

**Comment by ImAxel0** [comment]
The infinite loop is fine, it's just waiting for a game to load, but it shouldn't crash when you run a game. At which point does it crash in the loading screen?

**Comment by tmenant** [comment]
The game crashes just after i selected my save and clicked on it to run the game. I juste have time to see to host's menu and boom, the game shuts down...

**Comment by ImAxel0** [comment]
Really strange. If it crash it should be at about half of the loading screen since it doesn't do anything before that. Have you tried to set the game in borderless window mode?

**Comment by mcp43** [comment]
Hi hi - Experiencing a similar issue - I understand the infinite loop spam, as it's just looking for my player, however, once the save is loaded, it shows everything successful in the console, shows it's created all the hooks etc. However, the game crashes upon loading into the world after about 2 seconds. I can see my values in the bottom left (Stamina, Hunger, Thirst, etc. all changed and such) - but then the game simply crashes.
I followed all the directions, I've run the game in Windowed (There is no "Borderless" option, just Fullscreen & Windowed). Not quite sure what else to do, but it doesn't seem to want to run properly without immediately crashing.

**Comment by ImAxel0** [comment]
> Hi hi - Experiencing a similar issue - I understand the infinite loop spam, as it's just looking for my player, however, once the save is loaded, it shows everything successful in the console, shows it's created all the hooks etc. However, the game crashes upon loading into the world after about 2 seconds. I can see my values in the bottom left (Stamina, Hunger, Thirst, etc. all changed and such) - but then the game simply crashes. I followed all the directions, I've run the game in Windowed (There is no "Borderless" option, just Fullscreen & Windowed). Not quite sure what else to do, but it doesn't seem to want to run properly without immediately crashing.

Hi, the mod has been discontinued since we now have a site for Sons of the Forest mods where I uploaded a better version of this mod menu here [https://sotf-mods.com/mods/imaxel/axel's-mod-menu](https://sotf-mods.com/mods/imaxel/axel's-mod-menu). All mods on site uses a mod loader called RedLoader made by a member of the modding community.
