### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by PanetiX** [ImAxel0/SOTFmenu#5]
hey i installed the mod with Thunderstore but nothing happen when i press "P" ingame.

**Comment by ImAxel0** [comment]
> hey i installed the mod with Thunderstore but nothing happen when i press "P" ingame.

The mod is depreceted and won't be updated since it has been substituted with [this one](https://sotf-mods.com/mods/imaxel/axel's-mod-menu) which uses a mod loader made for SonsOfTheForest called RedLoader.
