### ISSUE TITLE
cannot escape interactive map teleport 

### ISSUE THREAD

**Issue by TTVMinnieMagma** [ImAxel0/SOTFmenu#6]
i tryed using the interactive map to teleport to keven when he ran off but when i try to turn off the interactive map it wont let me

**Comment by ImAxel0** [comment]
You are probably playing on a resolution > 1080p which from what I remember can have this problem. Anyway this mod menu is outdated and you shouldn't really use it but [this](https://sotf-mods.com/mods/imaxel/axel's-mod-menu) instead. But right now all mods have problems so it's better to wait for a fix.
